### ISSUE TITLE
JSON example

### ISSUE THREAD

**Issue by gevhambarzumyan93** [pixijs/spine-v8#16]
### Problem
It is a bit hard to handle JSON. (I tried with Raptor and almost broke my monitor.)

### Solution
Please create an example JSON file. (You already added a Raptor asset for that.)

**Comment by Zyie** [comment]
Hi, we are only trying to copy what is in the official spine runtime repo. If you need a specific example made please add your issue to the main project:

https://github.com/EsotericSoftware/spine-runtimes

**Comment by gevhambarzumyan93** [comment]
I already find the solution so could you add it to your example files if i pass it to you?

**Comment by vlasenkoigor** [comment]
> I already find the solution so could you add it to your example files if i pass it to you?

Do you have the one? Can you share please ?

**Comment by gevhambarzumyan93** [comment]
> Do you have the one? Can you share please?

[this is the working version](https://github.com/gevhambarzumyan93/react-spine/blob/main/src/Character/baseJsonCharacter.js)

this handles the main part
```
 const attachmentLoader = new AtlasAttachmentLoader(Assets.get(atlas));
    const spineJsonParser = new SkeletonJson(attachmentLoader);

    const skeletonData = spineJsonParser.readSkeletonData(Assets.get(skeleton));

    this.spine = new Spine(skeletonData);
    ```

**Comment by vlasenkoigor** [comment]
> > Do you have the one? Can you share please?
> 
> [this is the working version](https://github.com/gevhambarzumyan93/react-spine/blob/main/src/Character/baseJsonCharacter.js)
> 
> this handles the main part
> 
> ```
>  const attachmentLoader = new AtlasAttachmentLoader(Assets.get(atlas));
>     const spineJsonParser = new SkeletonJson(attachmentLoader);
> 
>     const skeletonData = spineJsonParser.readSkeletonData(Assets.get(skeleton));
> 
>     this.spine = new Spine(skeletonData);
>     ```
> ```

thanks!!
