### ISSUE TITLE
The rendering in Phaser and Pixi appears differently.

### ISSUE THREAD

**Issue by peterlee-dev** [pixijs/spine-v8#2]
![스크린샷 2024-04-19 13 12 34](https://github.com/pixijs/spine-v8/assets/72899599/8f1078ff-7ffb-4b66-bc57-9fda15330a8b)
pixi
![스크린샷 2024-04-19 13 12 45](https://github.com/pixijs/spine-v8/assets/72899599/061e0849-e1da-496f-b6d7-5b7e74e6d338)
phaser

In Phaser, the character's ears look smooth, but in Pixi, I noticed that there are lines appearing on the ears during rendering. What could be the issue?

**Comment by GoodBoyDigital** [comment]
hey there! thanks for sharing, would you mind running this in the WebGL renderer pls? I think this may be a WebGPU alpha thing I need to look into!

**Comment by peterlee-dev** [comment]
I checked the renderer of the app and found out that it's using WebGL instead of WebGPU.

**Comment by GoodBoyDigital** [comment]
heya - i think this is a premultiplied alpha issue. if you can save out your images with non-pre-multiplied alpha. It should be a temporary fix!

**Comment by GoodBoyDigital** [comment]
hey @peterlee-dev would you mind sending the animation across please? will try to take a look at that this week! Thanks!

**Comment by peterlee-dev** [comment]
How should I deliver the animation? If you need the file, please let me know your email address.

**Comment by GoodBoyDigital** [comment]
tbh - I probably only need the texture! could you post that here? thanks! 
otherwise, we could chat on the discord?

**Comment by peterlee-dev** [comment]
I have sent the problematic Spine file to mat.groves@play.co. I also tested it with version 2.0.2, but encountered errors. Thank you for your assistance.
`Uncaught Error: String in string table must not be null.
    at SkeletonBinary.readSkeletonData (@pixi_spine-pixi.js?v=5b7827b7:8534:15)
    at _Spine.from (@pixi_spine-pixi.js?v=5b7827b7:12399:33)
    at main.ts:29:19`

**Comment by peterlee-dev** [comment]
It seems like the error is due to differences in Spine Editor versions.
There are no errors in Spine Core version 4.2.26.
However, the issue with the line being drawn is the same in previous versions as well.

**Comment by davidetan** [comment]
As GoodBoyDigital mention in a previous post, this is a premultiplied alpha issue that are currently loaded without taking this into consideration.
This PR (https://github.com/pixijs/spine-v8/pull/30) should address the problem.

However, you can export non premultiplied alpha textures as GoodBoyDigital suggested here:
> if you can save out your images with non-pre-multiplied alpha. It should be a temporary fix!

**Comment by davidetan** [comment]
The PR has been merged.
From Pixi v8.3.0 and the v2.0.3 of this library, pma loading is managed automatically.

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
