### ISSUE TITLE
Bug: pixijs container attached to a spine slot is not interactable

### ISSUE THREAD

**Issue by SteveFoxx** [pixijs/spine-v8#23]
The container which is added to a spine via .addSlotObject function doesn't seem to be interactable.

pixi.js v8.2.1
@pixi/spine-pixi v2.0.2

Repo: https://github.com/SteveFoxx/pixi-typescript-boilerplate-v8

**Comment by kkitov** [comment]
i have experienced the same problem

**Comment by kkitov** [comment]
@Zyie do you have thoughts on this

**Comment by Zyie** [comment]
hey everyone, this is a bug and we will look into this asap!

**Comment by daserra** [comment]
Hi @Zyie, as far as I could see the interaction stops once we flag the container that will be attached with this flag.
`container.includeInBuild = false;` as it is a internal pixi flag maybe we need to report it  pixi team? I couldn't find any information on what that flag does.
![image](https://github.com/user-attachments/assets/0583e18b-0315-4016-b058-3e51dcdffc1a)
when I comment that line, I still can interact with the container but the draw order is incorrect.

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
