### ISSUE TITLE
Bug: Clipping attachment prevents rendering of subsequent attachments in draw order

### ISSUE THREAD

**Issue by FacePlace** [pixijs/spine-v8#24]
Attachments in the draw order after a clipping attachment are not rendered in PixiJS, even if they aren't clipped themselves. This occurs despite all elements being visible in the Spine editor.

Everything on the right side of the portal is supposed to be visible, as it is in the editor.

![spineIssue2](https://github.com/pixijs/spine-v8/assets/43105109/cc4e14c2-63a5-4241-a8f0-71890da07f1d)

However, it looks like attachments after the clipping attachment in the draw order are not rendered in PixiJS.

![spineIssue1](https://github.com/pixijs/spine-v8/assets/43105109/418152a9-2bbd-4471-be4f-1d7cad552150)

Repo: https://github.com/FacePlace/pixi-spine-clipping-demo

pixi.js - 8.2.1
@pixi/spine-pixi  - 2.0.2

**Comment by alexbown** [comment]
I believe I am also having the same issue with clipping not applying to the correct slots, with animations looking fine in the skeleton viewer, but not when ran in pixi. (I had some discussion on the matter in the PixiJS discord in the pixi-spine channel).
![image](https://github.com/user-attachments/assets/2b7ef846-8dbd-45ae-8898-a1dd338c6334)

**Comment by davidetan** [comment]
This PR (https://github.com/pixijs/spine-v8/pull/29) should address the problem.
Not 100% sure will address all problems because I don't have access to your assets.
