### ISSUE TITLE
How to set PremultiplyAlpha？

### ISSUE THREAD

**Issue by littletommytan** [pixijs/spine-v8#25]

**Comment by davidetan** [comment]
When this PR (https://github.com/pixijs/spine-v8/pull/30) is merged, pma textures can be loaded without doing anything in particular.

**Comment by davidetan** [comment]
From Pixi v8.3.0 and the v2.0.3 of this library, pma loading is managed automatically.

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
