### ISSUE TITLE
Spine Animation that works on pixi 7 and 6 doesn't work on pixi 8

### ISSUE THREAD

**Issue by apelev** [pixijs/spine-v8#26]
Hello guys. I am currently trying to run some spine animations after migration from pixi 7 to pixi 8. Some weird artifacts appear (looks like scaling or improper reading of the spritesheet coordinates). I am attaching a screenshot of a moment when such artifact appears. The fiery outline should appear on the lemon, not "moved" away from it. The interesting thing is that if I enable the spine debug with the following setup( everything is disabled), the animation starts to appear properly. Once I disable the debugger it bugs again.
```

public static attachSpineDebug(spine: Spine): void {
    const debug = new SpineDebugRenderer();

    debug.drawRegionAttachments = false;
    debug.drawMeshTriangles = false;
    debug.drawMeshHull = false;
    debug.drawBones = false;
    debug.drawPaths = false;
    debug.drawBoundingBoxes = false;
    debug.drawClipping = false;
    debug.drawEvents = false;
    spine.debug = debug;
  }

```
how it is >>>>
![image](https://github.com/user-attachments/assets/ae58370f-8bf4-48c9-ac47-076e7162b882)

I have tried several combinations of pixijs and spine v8 plugin but none seem to fix the issue. Currently trying with pixi 8.2^ and spine pixi 2.0.2.
The spine version is 4.2.33

We tried exporting in several different formats and versions from the spine editor and none seem to work. The animation itself runs fine in spine editor and as I previously mentioned with pixi 7 and pixi 6.

Any ideas what could possibly be done to fix this issue ? I can also provide the animation in private if it would help

**Comment by sbyps** [comment]
+1

**Comment by davidetan** [comment]
That's difficult to debug without the animation. I can work on that, if you can provide the animation to me.

**Comment by apelev** [comment]
> That's difficult to debug without the animation. I can work on that, if you can provide the animation to me.

Hello, mate. Here is a WeTransfer link to it https://we.tl/t-10IEYNR8Yp

**Comment by davidetan** [comment]
Thanks for providing your asset. I was able to find the problem and a solution and I just quickly created a draft PR. More info into the PR here: https://github.com/pixijs/spine-v8/pull/31

Tomorrow, I'll see if I can do that in a cleaner way.

**Comment by sbyps** [comment]
i also get some problem，when i use this spine resource, cannot render as well in pixi7;
https://conan-online.fbcontent.cn/webapp/conan-math-page/little-teacher/v4/little_teacher.skel

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
