### ISSUE TITLE
Any example on how to use this?

### ISSUE THREAD

**Issue by ziarmandhost** [pixijs/spine-v8#3]
I have next setup: vite + pixijs + typescript

package.json:
```json
"dependencies": {
    "@pixi/spine-pixi": "^1.0.8",
    "pixi.js": "^8.1.1"
  }
```

main.ts:
```ts
import "@pixi/spine-pixi"
import {Application, Assets} from "pixi.js"
import {Spine} from "@pixi/spine-pixi"
import "./style.css"

const app = new Application()
await app.init({
    resizeTo: document.body
})
document.body.appendChild(app.canvas)

await Assets.load("spineboy-pro.atlas")
await Assets.load("spineboy-pro.png")
await Assets.load("spineboy-pro.json")

const spineboy = Assets.get("spineboy-pro.json")
const test = new Spine(spineboy) 
console.log(test)
```

How to use this package? I see error on console (file attached). Any guide how to setup it?

![image](https://github.com/pixijs/spine-v8/assets/30569343/df2e87f9-6fa1-4123-9255-0111e652cb37)

**Comment by ziarmandhost** [comment]
сс: @GoodBoyDigital @Zyie

**Comment by peterlee-dev** [comment]
"You can check the example here: https://github.com/pixijs/spine-v8/blob/main/examples/index.html"

**Comment by Zyie** [comment]
Hey @ziarmandhost we have now updated all of the examples on this repo to work properly with v8

**Comment by a982246809** [comment]
> You can check the example here: https://github.com/pixijs/spine-v8/blob/main/examples/index.html您可以在此处查看示例：https://github.com/pixijs/spine-v8/blob/main/examples/index.html
There is no example about json
没有关于json的示例

**Comment by cleverocheck** [comment]
I have the issue with webpack. Probably loader doesn't connect due to builder.
