### ISSUE TITLE
esotericsoftware introduced breaking change causing masks to not work

### ISSUE THREAD

**Issue by daserra** [pixijs/spine-v8#33]
Hi guys,

The esotericsoftware team introduced a breaking change by changing a signature of a method from their runtime 4.2.45 to 4.2.56. Now I'm experiencing some issues with masks in all my animations. 

On version 4.2.45 we had
```typescript
clipTriangles(vertices, verticesLength, triangles, trianglesLength, uvs, light, dark, twoColor)  ....
``` 

On version 4.2.56 we have
```typescript
clipTriangles(vertices, triangles, trianglesLength, uvs, light, dark, twoColor) ....
```

**Comment by Zyie** [comment]
Hey @davidetan is this a known issue? 
I was under the assumption that `patch` versions of spine were not breaking changes, maybe I'm wrong about that?

**Comment by davidetan** [comment]
> Hey @davidetan is this a known issue? I was under the assumption that `patch` versions of spine were not breaking changes, maybe I'm wrong about that?

That should not have happened. There should be the deprecated version of the function, but it's missing. Let me see what happened and I'll be back here with more info.

**Comment by davidetan** [comment]
We just published 4.2.57 where we restored the old signature and marked it as deprecated. Sorry for the trouble and thanks for letting us know!

**Comment by daserra** [comment]
Thanks guys, tho that particular problem is fixed I still have a problem with masks. I will try to explain as the animator told me it may be related to the endSlot of the mask not working correctly. 
<img width="1343" alt="image" src="https://github.com/user-attachments/assets/712a1b1b-5a49-49b9-bb92-a447e4b49d3a">
That is how the animation looks when the endSlot is working correctly.

Here the animator selected an wrong endSlot as the first one then the result is very similar with the result I have when I import the animation to my project.
<img width="1376" alt="image" src="https://github.com/user-attachments/assets/c0aad8de-2ad6-4070-b837-6593720d5960">
Here is when adding that animation to one of pixi-spine examples
![image](https://github.com/user-attachments/assets/9d425d6d-3d85-4861-a07e-e72d212b5312)

**Comment by daserra** [comment]
Hi guys thanks for that! 
Tho that issue is fixed I still have a problem with masks which I believe is related to endSlot.

The animator created an animation where we can reproduce the issue.
![image](https://github.com/user-attachments/assets/97418578-8c7e-4e65-b13d-ff3f4074a31f)
Here we expect only the white box to affected by the mask, I'm not that familiar with spine but the animator told me that regarding the drawing order and selecting the endSlot correctly you can achieve that.

For some reason the green boxes are not correctly rendered and are effected by the mask when it shouldn't be.

You can reproduce the issue [here](https://araucariagames.github.io/projects/house/examples/physics4.html)

**Comment by davidetan** [comment]
@daserra Just sent a PR: #34
That made me discover another bug. The white square that should disappear, remained stuck in the middle of the jump. The PR fixes also that.

Many thanks for reporting this!

**Comment by daserra** [comment]
Thank you for the quick fix!

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
