### ISSUE TITLE
spine animation not work when have clipping mask

### ISSUE THREAD

**Issue by stanleySHU** [pixijs/spine-v8#36]
if spine exist clipping mask feature, the animation not work well. it is work on v7, but not work on v8.

on v7
@esotericsoftware/spine-pixi": "^4.2.56"
"pixi.js": "^8.2.6

on v8
@esotericsoftware/spine-pixi": "^4.2.56"
@pixi/spine-pixi": "^2.0.3"
"pixi.js": "^8.2.6

and i change pixijs to 8.1.2, same issue

The content that needs to be cropped cannot be displayed

**Comment by davidetan** [comment]
Hello, are you referring to Spine clipping attachments?

If yes, there is this PR https://github.com/pixijs/spine-v8/pull/34 that fixes a bug with them. I suppose this is the problem you are having.

If that does not fix it, I need a way to reproduce the issue. You could set up a minimum reproduction project, or you can just send me the assets here or privately.

**Comment by davidetan** [comment]
Ok, I'll wait for the repro project then.

**Comment by stanleySHU** [comment]
fixed in latest version
