### ISSUE TITLE
Objects added to Slots can't be manipulated as it was in previous version.

### ISSUE THREAD

**Issue by daserra** [pixijs/spine-v8#39]
Hi guys,

Currently when attaching a container to a a slot I can't change some of container properties like scale and position, it looks like something is reseting the properties in the container, some properties like alpha for example works. It is something very useful that could be done on previous version.

It can easily be reproduced in the test project https://pixijs.io/spine-v8/examples/slot-objects.html you just need to include this line of code.

`spineboy.addSlotObject("gun", logo1);`
`const gun = spineboy.getSlotObject("gun");`
`gun.scale.set(0.5);`

Maybe is related to https://github.com/pixijs/spine-v8/issues/23 ?

**Comment by daserra** [comment]
Ok I found the part of code where you actually apply the bones properties to the container. I manage to achieve what I want by wrapping my object in to a separated container and attaching that container to the slot then I can manipulate the child object as desired.

**Comment by davidetan** [comment]
Yup, exactly. It's designed like that. This is from the documentation:

> It is possible to assign only one Pixi object per slot. Once the Pixi object has been added, its transform will be automatically modified by the Spine object.
To have more control over the added objects, you can add a Pixi Container where you are free to add as many Pixi objects as you want, offset their position, angle, scale, and so on.
