### ISSUE TITLE
Document: add performance example

### ISSUE THREAD

**Issue by furic** [pixijs/spine-v8#40]
It would be nice if there's a performance showcase, similar to v8's bunny example.
![image](https://pixijs.com/assets/images/image-72e0ca7d8183d62c10a0f5e8dcc4ebda.png)

I quickly did [mine](https://github.com/furic/spine-v8/commit/ce8071892c0ff20fa8727ad1bd102244bfa84350), pretty impressive outcome:
1000 spaceboys animating `idle`, `run` and `hoverboard` randomly.
v8 - 58.8fps
v7 - 36.0fps
![v7-vs-v8](https://i.imgur.com/Mi9gQGp.jpeg)

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
