### ISSUE TITLE
Added slot container doesn't follow original slot's alpha

### ISSUE THREAD

**Issue by joshsurin** [pixijs/spine-v8#44]
### Issue
When adding a PIXI Object to a slot with `addSlotObject`, the added PIXI Object's alpha remains at 1, even when the origin slot's alpha changes.

EsotericSoftware implements this by matching the alpha in the `updatePixiObject` function: 

```pixiObject.alpha = this.skeleton.color.a * slot.color.a;```

The same can be achieved by adding this to the equivalent `updateSlotObject` function:

```container.alpha = this.skeleton.color.a * slot.color.a```

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
