### ISSUE TITLE
`gpuSpineData` is undefined in SpinePipe (question)

### ISSUE THREAD

**Issue by alvov-evo** [pixijs/spine-v8#48]
I observe a certain case when rendering a spine throws this error for me:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'slotBatches')
    at SpinePipe.validateRenderable
    at Module.validateRenderables
    at RenderGroupSystem.render
    at SystemRunner.emit
    at WebGLRenderer.render
    at _Application.render
    at TickerListener.emit
    at _Ticker.update
    at _tick
``` 
When I debug I see that `this.gpuSpineData` is undefined because in SpinePipe `validateRenderable` is being called before `addRenderable`.

I suppose `addRenderable` should always happen before `validateRenderable` in pixi.js? But then maybe not, because I see that MeshPipe and SpritePipe have certain precautions for cases when data they need are missing.

So I was wondering: is it something to do with my application, or should there be checks in SpinePipe.ts that `gpuSpineData` is defined?

Thank you.

**Comment by rmercesGazeus** [comment]
I’m encountering the same issue, and my canvas turns black for a single frame when it occurs.
In my case:
```
TypeError: Cannot read properties of undefined (reading 'texture')
    at SpinePipe.validateRenderable (SpinePipe.mjs:38:1)
    at validateRenderables (validateRenderables.mjs:9:1)
    at RenderGroupSystem.render (RenderGroupSystem.mjs:35:28)
    at SystemRunner.emit (SystemRunner.mjs:19:1)
    at WebGPURenderer.render (AbstractRenderer.mjs:89:1)
```

```
validateRenderable(spine) {
    spine._applyState();
    if (spine.spineAttachmentsDirty) {
      return true;
    } else if (spine.spineTexturesDirty) {
      const drawOrder = spine.skeleton.drawOrder;
      const gpuSpine = this.gpuSpineData[spine.uid];
      for (let i = 0, n = drawOrder.length; i < n; i++) {
        const slot = drawOrder[i];
        const attachment = slot.getAttachment();
        if (attachment instanceof RegionAttachment || attachment instanceof MeshAttachment) {
          const cacheData = spine._getCachedData(slot, attachment);
          const batchableSpineSlot = gpuSpine.slotBatches[cacheData.id];
          const texture = cacheData.texture;
          if (texture !== batchableSpineSlot.texture) { <<<<<<<<<<<<<<< ERROR
            if (!batchableSpineSlot._batcher.checkAndUpdateTexture(batchableSpineSlot, texture)) {
              return true;
            }
          }
        }
      }
    }
    return false;
  }
```

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
