### ISSUE TITLE
Is Spine 3.8 not supported?

### ISSUE THREAD

**Issue by akio7624** [pixijs/spine-v8#49]
When loading Spine 4.2 and Spine 3.8, version 4.2 loads without any issues, but version 3.8.96 causes the following error:

```
Uncaught (in promise) Error: String in string table must not be null.
    at SkeletonBinary.readSkeletonData (SkeletonBinary.ts:97:20)
    at _Spine.from (Spine.ts:857:37)
    at myfunc (main.js:212:38)
```

The file opens correctly in other viewers that support version 3.8, so there doesn't appear to be an issue with the file itself. Does this only support version 4.x?

I'm using `pixi.js@8.5.2` with this `spine-pixi.js`.

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
