### ISSUE TITLE
Clipping masks artifacts

### ISSUE THREAD

**Issue by vlasenkoigor** [pixijs/spine-v8#50]
Hi 

I have reviewed current issues and saw that issue with clipping mask was fixed already, but even now I encounter some artifacts on animation whilst mask is applied, please check the attachment video. Is it known issue ? 

https://github.com/user-attachments/assets/e601991c-690a-424a-a230-409316d2d1a2

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`

**Comment by vlasenkoigor** [comment]
Thanks! Appreciate it
