### ISSUE TITLE
Atlas loader uses the wrong local directory for texture loading

### ISSUE THREAD

**Issue by nekroadmin** [pixijs/spine-v8#51]
### Current Behavior

I'm trying to load the sack asset (from the examples folder), but I’m facing an issue because my project export path (`./dist/`) differs from the path used for assets. This discrepancy seems to interfere with locating the PNG file specified in the atlas file, leading to lookup issues.

![Image](https://github.com/user-attachments/assets/5b19ee5e-26a6-4e83-bfff-b9e39eaf8b0b)

### Expected Behavior

The asset should load correctly from the specified path in the atlas file, regardless of the project export path.

### Possible Solution

To address this, I modified `atlasLoader.js` at line 50, changing it to:
 `const url = providedPage ?? basePath + pageName;`

This adjustment seems to resolve the issue, but I'm not certain if it could cause any other unintended side effects.

### Question

Is there a recommended solution for this scenario, or is there a more robust way to handle paths in this setup? Also, could the modification above introduce any issues elsewhere?

### Environment

- **`pixi.js` version**: *8.5.2*
- **`spine-pixi` version**: *2.1.1*
- **Browser & Version**: *130.0.6723.117 (64-bit)*
- **OS & Version**: *Windows 11 10.0.22631*

**Comment by Zyie** [comment]
Hi

We have now moved this project to the official Esoteric Software repo for them to maintain. As a result we will be archiving this repo and closing all issues. If you still are having this issue please feel free to open an issue over on the new repo!

- [New Repo](https://github.com/EsotericSoftware/spine-runtimes)

As for migrating between the projects it should be as simple as swapping out the imports from `@pxi/spine-pixi` to `@esotericsoftware/spine-pixi-v8`
