### ISSUE TITLE
[Question] Will this repository continue, or should it be archived?

### ISSUE THREAD

**Issue by yordan-kanchelov** [pixijs/spine-v8#53]
Since everything here has been merged into Esoteric's repository, I wanted to ask:

- Will this repository continue to exist and be supported?
- Should we instead focus on Esoteric's repository, directing issues there?

If the latter is true, would it make sense to archive this repository to avoid confusion for newcomers?

**Comment by Zyie** [comment]
Hey, I am in the process of archiving the repo now!

Yes any issues should be directed to the esoteric repo
