### ISSUE TITLE
Use `Skeleton.yDown = true;` instead of negating y coordinates everywhere

### ISSUE THREAD

**Issue by badlogic** [pixijs/spine-v8#9]
It seems the line `Skeleton.yDown = true;` from `Spine.ts` got smoked some time during this port.

`Skeleton.yDown = true;` will ensure that every kind of position is calculated with the assumption that the y-axis is pointing downward.

That way you can avoid all those manual negations of y-coordinates everywhere (and other methods exposed by the skeleton itself won't need manualy inversion by the user).

**Comment by GoodBoyDigital** [comment]
good to know - will adjust. The manual negations were making me sad too!
